version: '3'
services:
  go:
    image: golang:1.22
    volumes:
      - type: bind
        source: .
        target: /go/src
    tty: true
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    ports:
      - ":3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: design_pattern
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf